# Generated by Django 3.2.8 on 2021-11-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='context',
        ),
        migrations.RenameField(
            model_name='languageprogramming',
            old_name='lg_key',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='context',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_key',
        ),
        migrations.RemoveField(
            model_name='languageprogramming',
            name='lg_title',
        ),
    ]
