# Generated by Django 3.2.7 on 2021-09-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_corrected',
            field=models.BooleanField(default=False),
        ),
    ]
