# Generated by Django 3.2.7 on 2021-09-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_rename_is_corrected_choice_is_corrected_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='is_corrected_answer',
            new_name='is_correct_answer',
        ),
    ]
