# Generated by Django 3.2.7 on 2021-09-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_rename_is_corrected_answer_choice_is_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_correct_answer',
            field=models.BooleanField(),
        ),
    ]
