# Generated by Django 3.2.8 on 2021-11-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_rename_date_userscore_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LanguageProgramming',
            new_name='ProgrammingLanguage',
        ),
    ]
