# Generated by Django 3.2.8 on 2021-11-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0005_rename_languageprogramming_programminglanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.TextField(null=True),
        ),
    ]
