# Generated by Django 3.2.8 on 2021-11-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0006_alter_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='average_time',
            field=models.FloatField(default=0),
        ),
    ]
