# Generated by Django 3.2.7 on 2021-09-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0007_auto_20210927_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_score',
            field=models.IntegerField(default=0),
        ),
    ]
