# Generated by Django 3.2.7 on 2021-09-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0008_category_category_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_score',
            field=models.IntegerField(),
        ),
    ]
